recast:
  tags:
  - docker-privileged
  services:
  - docker:19.03.1-dind
  image: recast/recastatlas:v0.1.0
  variables:
   RECAST_DEFAULT_RUN_BACKEND: local
  script:
  # add my workflow
  - $(recast catalogue add $PWD)
  - recast catalogue ls
  - recast catalogue describe examples/helloworld
  - recast catalogue check examples/helloworld
  
  # run the workflow
  - recast run examples/helloworld --tag myrun
  artifacts:
    paths:
    - recast-myrun
    expire_in: 1 day
    when: always
