recast:
  tags:
  - docker-privileged
  services:
  - docker:stable-dind
  stage: build
  image: "recast/recastatlas:v0.0.20"
  script:
  # add my workflow
  - $(recast catalogue add $PWD)
  - $(recast auth write --basedir auth)

  - recast catalogue ls
  - recast catalogue describe tutorial/myrecast
  - recast catalogue check tutorial/myrecast

  # run the test

  - recast tests run tutorial/myrecast test_eventselection --tag myevseltest
  - recast tests run tutorial/myrecast test_statanalysis --tag mystattest

  # run the workflow

  - recast run tutorial/myrecast --example default --tag myworkflowrun

  artifacts:
    paths:
    - recast-test-myevseltest
    - recast-test-mystattest
    - recast-myworkflowrun
    expire_in: 1 day
    when: always

