stages:
- name: stanalysiscode
  dependencies: [init]
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      inputfile: {step: init, output: dxaod_file}
      submitDir: submitDirMAIN
      outputdir_minintuple: '{workdir}/input_files/user.othrif.vXX.999999.VBFHAltSignal.root'
    step: {$ref: 'steps.yml#/stanalysiscode'}

- name: stpostprocessing
  dependencies: [init, stanalysiscode]
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      input_directory: {step: stanalysiscode, output: MiniNtuple}
      outputdir_MicroNtuple: '{workdir}/MicroNtuple_signal'
      outputfile_MicroNtuple: 'VBFHAltSignal-MicroNtuple.root'
      outputdir_HF: '{workdir}/HF_signal'
      outputfile_HF: 'HFVBFHAltSignalNominal.root'
    step: {$ref: 'steps.yml#/stpostprocessing'}

- name: limitsetting
  dependencies: [init, stpostprocessing]
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      input_directory: {step: stpostprocessing, output: HFoutput}
      input_file: {step: stpostprocessing, output: outputfile_HF}
      log_limit_HF: '{workdir}/limit_files'
    step: {$ref: 'steps.yml#/limitsetting'}