stages:
- name: stanalysiscode
  dependencies: [init]
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      name: recast-vbfmet-stanalysiscode
      submitDir: '{workdir}/submitDir'
    step: {$ref: 'steps.yml#/stanalysiscode'}

- name: stpostprocessing
  dependencies: [init, stanalysiscode]
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      name: recast-vbfmet-stpostprocessing
      input_directory: {step: stanalysiscode, output: HF_files}
    step: {$ref: 'steps.yml#/stpostprocessing'}

- name: statanalysis
  dependencies: [stanalysiscode, stpostprocessing, init]
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      input_histfitter: '{workdir}/HF_files'
      signal_file: {step: stpostprocessing, output: HF_files }
      background_file: exampleFile/HF_jan7_mc16all_nom.root
      resultdir: '{workdir}/fitresults'
    step: {$ref: 'steps.yml#/statanalysis'}
