stages:
- name: stanalysiscode
  dependencies: [init]
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      inputfile: {step: init, output: dxaod_file}
      submitDir: '{workdir}/submitDir'
      outputdir_minintuple: '{workdir}/input_files/user.othrif.vXX.999999.VBFHAltSignal.root'
    step: {$ref: 'steps.yml#/stanalysiscode'}

- name: stpostprocessing
  dependencies: [init, stanalysiscode]
  scheduler:
    scheduler_type: singlestep-stage
    parameters:
      name: recast-vbfmet-stpostprocessing
      input_directory: {step: stanalysiscode, output: MiniNtuple}
      outputdir_HF: '{workdir}/HF_files'
      outputfile_HF: 'HFVBFHAltSignalNominal.root'
    step: {$ref: 'steps.yml#/stpostprocessing'}